"use client";

import { FormEvent, useState } from "react";
import { ApiError, rejectRecommendation, updateGoal } from "@/lib/api";

export function DashboardControls({ goalId, initialMinutes }: { goalId: string; initialMinutes: number }) {
  const [minutes, setMinutes] = useState(String(initialMinutes)); const [paused, setPaused] = useState(false); const [reason, setReason] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function saveSettings(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); setMessage(""); try { const response = await updateGoal(goalId, { daily_minutes: Number(minutes), paused }); setMinutes(String(response.goal.daily_minutes)); setPaused(response.paused); setMessage(response.paused ? "Goal paused." : "Daily availability saved."); } catch (caught: unknown) { setError(caught instanceof ApiError ? caught.message : "Goal settings could not be saved."); } finally { setPending(false); } }
  async function reject() { if (!reason.trim()) { setError("Add a reason so the planner can learn from this signal."); return; } setPending(true); setError(""); setMessage(""); try { const response = await rejectRecommendation(goalId, reason.trim()); setMessage(response.message); setReason(""); } catch (caught: unknown) { setError(caught instanceof ApiError ? caught.message : "The recommendation could not be rejected."); } finally { setPending(false); } }
  return <section className="control-panel" aria-labelledby="controls-heading"><div className="section-kicker">Human controls</div><h2 id="controls-heading">Keep the route yours</h2><form onSubmit={saveSettings}><div className="field-grid"><div className="field"><label htmlFor="available-minutes">Daily availability</label><input id="available-minutes" type="number" min={5} max={240} value={minutes} onChange={(event) => setMinutes(event.target.value)} /></div><div className="field"><label className="format-option" htmlFor="pause-goal"><input id="pause-goal" type="checkbox" checked={paused} onChange={(event) => setPaused(event.target.checked)} /> Pause this goal</label></div></div><button className="primary-action" type="submit" disabled={pending}>Save availability</button></form><div className="field" style={{ marginTop: "1.5rem" }}><label htmlFor="reject-reason">Reject this recommendation <span className="label-note">Tell the planner why</span></label><textarea id="reject-reason" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="I need a shorter route today." /></div><button className="danger-action" type="button" onClick={reject} disabled={pending}>Send rejection</button><div aria-live="polite" aria-atomic="true">{message ? <p className="form-message">{message}</p> : null}{error ? <p className="error-message" role="alert">{error}</p> : null}</div></section>;
}
