/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Goal */
        post: operations["create_goal_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_goals__goal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Goal */
        patch: operations["update_goal_goals__goal_id__patch"];
        trace?: never;
    };
    "/goals/{goal_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_goals__goal_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goal_id}/diagnostic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diagnostic */
        post: operations["diagnostic_goals__goal_id__diagnostic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goal_id}/diagnostic/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diagnostic Answers */
        post: operations["diagnostic_answers_goals__goal_id__diagnostic_answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goal_id}/next-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Session */
        get: operations["next_session_goals__goal_id__next_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goal_id}/recommendations/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Recommendation */
        post: operations["reject_recommendation_goals__goal_id__recommendations_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goal_id}/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research */
        post: operations["research_goals__goal_id__research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goal_id}/simulate-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Day */
        post: operations["simulate_day_goals__goal_id__simulate_day_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goal_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_goals__goal_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/alternative-explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Alternative Explanation */
        post: operations["alternative_explanation_sessions__session_id__alternative_explanation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/assess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess */
        post: operations["assess_sessions__session_id__assess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Feedback */
        post: operations["session_feedback_sessions__session_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssessmentItem */
        AssessmentItem: {
            /** Concept Id */
            concept_id: string;
            /** Expected */
            expected: string;
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /** Id */
            id: string;
            /** Options */
            options?: string[];
            /** Question */
            question: string;
        };
        /** AssessmentResult */
        AssessmentResult: {
            /** Concept Id */
            concept_id: string;
            /** Correct */
            correct: number;
            /** Evidence */
            evidence?: string[];
            /** Misconceptions */
            misconceptions?: string[];
            /** Score */
            score: number;
            /** Total */
            total: number;
        };
        /**
         * AuthorityType
         * @enum {string}
         */
        AuthorityType: "official" | "vendor" | "book" | "blog" | "tutorial" | "forum" | "unknown";
        /**
         * BlockKind
         * @enum {string}
         */
        BlockKind: "concept" | "worked_example" | "practice" | "retrieval" | "review";
        /** Concept */
        Concept: {
            /**
             * Estimated Minutes
             * @default 15
             */
            estimated_minutes: number;
            /** Id */
            id: string;
            /**
             * Importance
             * @default 0.5
             */
            importance: number;
            /** Name */
            name: string;
            /** Prerequisites */
            prerequisites?: string[];
        };
        /**
         * ConceptState
         * @enum {string}
         */
        ConceptState: "unseen" | "introduced" | "weak" | "developing" | "mastered" | "review_due";
        /**
         * DeadlineStatus
         * @enum {string}
         */
        DeadlineStatus: "on_track" | "at_risk" | "infeasible";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LearnerConceptState */
        LearnerConceptState: {
            /** Concept Id */
            concept_id: string;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence?: string[];
            /** Last Assessed */
            last_assessed?: string | null;
            /** Last Seen */
            last_seen?: string | null;
            /** Mastery */
            mastery: number;
            /** Misconceptions */
            misconceptions?: string[];
            /** Next Review */
            next_review?: string | null;
            state: components["schemas"]["ConceptState"];
        };
        /** LearnerModel */
        LearnerModel: {
            /** Concepts */
            concepts?: {
                [key: string]: components["schemas"]["LearnerConceptState"];
            };
            /** Goal Id */
            goal_id: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** LearningGoal */
        LearningGoal: {
            /** Daily Minutes */
            daily_minutes: number;
            /**
             * Deadline
             * Format: date
             */
            deadline: string;
            /** Id */
            id: string;
            /** Preferred Formats */
            preferred_formats?: string[];
            /** Purpose */
            purpose: string;
            /** Success Criteria */
            success_criteria?: string[];
            /** Title */
            title: string;
        };
        /**
         * NextSessionDecision
         * @description Output of CurriculumPlanner, scored by NSDQ.
         */
        NextSessionDecision: {
            /** Blocks */
            blocks: components["schemas"]["SessionBlock"][];
            deadline_status: components["schemas"]["DeadlineStatus"];
            /** Deferred Concepts */
            deferred_concepts?: string[];
            /** Id */
            id?: string | null;
            /** Rationale */
            rationale: string;
            /** Reviews Included */
            reviews_included?: string[];
            /**
             * Session Date
             * Format: date
             */
            session_date: string;
            /** Total Minutes */
            total_minutes: number;
        };
        /** SessionBlock */
        SessionBlock: {
            /** Concept Id */
            concept_id: string;
            /** Content */
            content?: string | null;
            kind: components["schemas"]["BlockKind"];
            /** Minutes */
            minutes: number;
            /** Objective */
            objective: string;
            /** Source Ids */
            source_ids?: string[];
        };
        /** Source */
        Source: {
            authority: components["schemas"]["AuthorityType"];
            /** Content Path */
            content_path?: string | null;
            /** Id */
            id: string;
            /** Published At */
            published_at?: string | null;
            /**
             * Retrieved At
             * Format: date
             */
            retrieved_at: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Version */
            version?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** _AcceptedResponse */
        _AcceptedResponse: {
            /** Accepted */
            accepted: boolean;
            /** Message */
            message: string;
        };
        /** _AlternativeExplanationResponse */
        _AlternativeExplanationResponse: {
            /** Content */
            content: string;
            /** Source Ids */
            source_ids: string[];
        };
        /** _Answer */
        _Answer: {
            /** Answer */
            answer: string;
            /** Item Id */
            item_id: string;
        };
        /** _AnswersRequest */
        _AnswersRequest: {
            /** Answers */
            answers: components["schemas"]["_Answer"][];
        };
        /** _AssessmentResponse */
        _AssessmentResponse: {
            learner_model: components["schemas"]["LearnerModel"];
            /** Results */
            results: components["schemas"]["AssessmentResult"][];
        };
        /** _DashboardResponse */
        _DashboardResponse: {
            deadline_status: components["schemas"]["DeadlineStatus"];
            /** Estimated Sessions */
            estimated_sessions: number;
            /** Next Review */
            next_review: string | null;
            /** On Track */
            on_track: boolean;
            /** Progress */
            progress: number;
            /**
             * Projected Completion
             * Format: date
             */
            projected_completion: string;
            /** Strong */
            strong: string[];
            /** Weak */
            weak: string[];
            /** Why */
            why: string;
        };
        /** _DiagnosticResponse */
        _DiagnosticResponse: {
            /** Items */
            items: components["schemas"]["AssessmentItem"][];
        };
        /** _Event */
        _Event: {
            /** Day */
            day: number;
            /** Kind */
            kind: string;
            /** Message */
            message: string;
        };
        /** _GoalDetailsResponse */
        _GoalDetailsResponse: {
            /** Concepts */
            concepts: components["schemas"]["Concept"][];
            goal: components["schemas"]["LearningGoal"];
            learner_model: components["schemas"]["LearnerModel"];
        };
        /** _GoalRequest */
        _GoalRequest: {
            /** Daily Minutes */
            daily_minutes: number;
            /**
             * Deadline
             * Format: date
             */
            deadline: string;
            /** Preferred Formats */
            preferred_formats?: string[];
            /** Purpose */
            purpose: string;
            /** Title */
            title: string;
        };
        /** _GoalResponse */
        _GoalResponse: {
            /** Concepts */
            concepts: components["schemas"]["Concept"][];
            goal: components["schemas"]["LearningGoal"];
        };
        /** _GoalUpdateRequest */
        _GoalUpdateRequest: {
            /**
             * Daily Minutes
             * @default 30
             */
            daily_minutes: number;
            /**
             * Paused
             * @default false
             */
            paused: boolean;
        };
        /** _GoalUpdateResponse */
        _GoalUpdateResponse: {
            goal: components["schemas"]["LearningGoal"];
            /** Paused */
            paused: boolean;
        };
        /** _LearnerResponse */
        _LearnerResponse: {
            learner_model: components["schemas"]["LearnerModel"];
        };
        /** _RecommendationRejectionRequest */
        _RecommendationRejectionRequest: {
            /** Reason */
            reason: string;
        };
        /** _ResearchRequest */
        _ResearchRequest: {
            /** Topic */
            topic: string;
        };
        /** _ResearchResponse */
        _ResearchResponse: {
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /** _SessionFeedbackRequest */
        _SessionFeedbackRequest: {
            /** Appropriate */
            appropriate: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** _SimulateDayRequest */
        _SimulateDayRequest: {
            /** Days */
            days: number;
        };
        /** _SimulateDayResponse */
        _SimulateDayResponse: {
            /** Events */
            events: components["schemas"]["_Event"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_goal_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_GoalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_GoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_GoalDetailsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_goal_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_GoalUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_GoalUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_goals__goal_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostic_goals__goal_id__diagnostic_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_DiagnosticResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostic_answers_goals__goal_id__diagnostic_answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_AnswersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_LearnerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_session_goals__goal_id__next_session_get: {
        parameters: {
            query: {
                today: string;
            };
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextSessionDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_recommendation_goals__goal_id__recommendations_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_RecommendationRejectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_AcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_goals__goal_id__research_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_ResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_day_goals__goal_id__simulate_day_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_SimulateDayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_SimulateDayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_goals__goal_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_ResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alternative_explanation_sessions__session_id__alternative_explanation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_AlternativeExplanationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assess_sessions__session_id__assess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_AnswersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_AssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_feedback_sessions__session_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_SessionFeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_AcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
